"""kode_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-di2WswP1rbnV6GXD-t5eYyklsHM55ej
"""

!pip install google-play-scraper

import pandas as pd
from google_play_scraper import Sort, reviews
from google.colab import files
import re

def scrape_playstore(app_id='com.shopee.id', jumlah=10000):
    # Scrape review PlayStore sebanyak 'jumlah' data
    result, _ = reviews(
        app_id,
        lang='id',
        country='id',
        sort=Sort.NEWEST,
        count=jumlah,
        filter_score_with=None
    )

    # Convert ke DataFrame
    df = pd.DataFrame(result)
    df = df[['content', 'score']]
    df.columns = ['text', 'rating']
    print(f"Scraping selesai, total data: {len(df)} review")
    return df

playstore_df = scrape_playstore('com.shopee.id', jumlah=10000)
playstore_df.head()

# Lihat distribusi rating (1-5)
playstore_df['rating'].value_counts().sort_index()

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'[\U00010000-\U0010ffff]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Terapkan ke hasil scraping (playstore_df)
playstore_df['clean_text'] = playstore_df['text'].apply(clean_text)
playstore_df[['text', 'clean_text']].sample(5)

def label_sentiment(rating):
    if rating <= 2:
        return 'Negatif'
    elif rating == 3:
        return 'Netral'
    else:
        return 'Positif'

playstore_df['sentiment'] = playstore_df['rating'].apply(label_sentiment)
playstore_df[['clean_text', 'rating', 'sentiment']].sample(5)

playstore_df['sentiment'].value_counts()

# Simpan data ke CSV
playstore_df.to_csv('playstore_reviews_shopee.csv', index=False)

# Download dataset
files.download('playstore_reviews_shopee.csv')